version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - siem_net

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.5
    container_name: wazuh.indexer
    ports:
      - "9205:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer
    networks:
      - siem_net

  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.5
    container_name: wazuh.manager
    hostname: wazuh.manager
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword1!
    depends_on:
      - wazuh.indexer
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_vodle:/var/ossec/vodle
    networks:
      - siem_net

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.5
    container_name: wazuh.dashboard
    ports:
      - "5602:5601"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - WAZUH_API_URL=https://wazuh.manager:55000
    depends_on:
      - wazuh.indexer
      - wazuh.manager
    volumes:
      - wazuh_dashboard_config:/usr/share/wazuh-dashboard/data/wazuh/config
    networks:
      - siem_net

volumes:
  es_data:
  wazuh_indexer_data:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_vodle:
  wazuh_dashboard_config:

networks:
  siem_net:
    driver: bridge
